- name: Install polaris cli on Linux
  import_tasks: linux.yml
  when: 
    - ansible_facts['os_family']|lower == 'redhat'

- name: Install polaris cli on Windows
  import_tasks: windows.yml
  when: 
    - ansible_facts['os_family']|lower == 'windows'
