---
# tasks file for polaris on Windows.

- name: Show polaris version
  win_shell: polaris -v
  register: command_result
  ignore_errors: True
- debug: var=command_result.stdout_lines[5]

- name: Remove polaris directory
  win_file: 
    path: "{{ polaris_path_win64 }}"
    state: absent

- name: Create polaris directory
  win_shell: mkdir {{ polaris_path_win64 }}

- name: Download {{ polaris_cli_win64 }}
  win_command: wget {{ polaris_cli_win64 }}
  args:
    chdir: "{{ polaris_path_win64 }}"

- name: Unzip polaris_cli-win64.zip
  win_shell: unzip polaris_cli-win64.zip
  args:
    chdir: "{{ polaris_path_win64 }}"

- name: Get polaris executeable path
  win_shell: 'ls {{ polaris_path_win64 }}/polaris_cli-win64-*/bin/'
  register: ls_result
- debug: "var=ls_result.stdout_lines[2]"

- name: Copy polaris.exe to bin\polaris
  debug:
    msg: "{{ ls_result.stdout_lines[2].split('    Directory: ')[1] }}"
- win_copy:
    src: "{{ ls_result.stdout_lines[2].split('    Directory: ')[1] }}\\bin\\polaris.exe"
    dest: "C:\\bin\\polaris\\polaris.exe"
    remote_src: yes

- name: Add polaris bin path to PATH
  win_path:
    elements: "C:\\bin\\polaris"
    state: present

- name: Show polaris version
  win_shell: polaris -v
  register: command_result
  ignore_errors: True
- debug: var=command_result.stdout_lines[5]
